[SDK-208][Node.js SDK] [EOS-54] Update README to mention Schema 2.2 changes
incountry/sdk-nodejs pull request #127
Opened 2020-08-25 13:18 UTC by igor-alekseev-dev

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-208](https://incountry.atlassian.net/browse/SDK-208)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version in package.json? What is the new version?

2020-08-26 11:42 UTC, RommeroInCountry commented on README.md
> +  encrypt?: boolean;       // If false, encryption is not used. If omitted is set to true.
If false, encryption is not used. Defaults to true.

2020-08-26 12:02 UTC, artemgolozubov approved these changes
LGTM

2020-08-26 12:08 UTC, RommeroInCountry requested changes

2020-08-26 12:08 UTC, RommeroInCountry commented on README.md
> +It returns a `Promise` which resolves to `{ record }`  or  rejects Promise if there is no record with this `recordKey`.
`read` returns a `Promise` which resolves to `{ record }`  or is rejected if there are no records for the given `recordKey`.

2020-08-26 12:56 UTC, artemgolozubov approved these changes
LGTM

2020-08-26 14:47 UTC, RommeroInCountry requested changes

2020-08-26 14:47 UTC, RommeroInCountry commented on README.md
> +#### Created and updated dates fields
simply "Date fields" would do

2020-08-26 14:47 UTC, RommeroInCountry commented on README.md
> +Fields `createdAt` and `updatedAt` store dates set by InCountry storage server. `createdAt` indicates when the data was first time processed in the target country. `updatedAt` indicates when last wri
Use `createdAt` and `updatedAt` fields to access date-related information about records. `createdAt` indicates date when the record was initially created in the target country. `updatedAt` shows the date of the latest write operation for the given `recordKey`

2020-08-27 10:47 UTC, artemgolozubov approved these changes
LGTM

2020-08-27 11:24 UTC, VladimirLevitskiy approved these changes
LGTM

2020-08-27 11:38 UTC, RommeroInCountry approved these changes
LGTM

2020-08-27 11:52 UTC, merged