SDK-80 [Node.js SDK] Add file upload/read methods
incountry/sdk-nodejs pull request #155
Opened 2020-09-11 10:29 UTC by igor-alekseev-dev

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-80](https://incountry.atlassian.net/browse/SDK-80)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version in package.json? What is the new version?

2020-09-30 13:39 UTC, RommeroInCountry requested changes

2020-10-01 10:36 UTC, igor-alekseev-dev commented on README.md
> +# InCountry Storage SDK [File Storage DRAFT]
@Rommero said if we don't have this comment QAs won't accept this docs %)

2020-10-01 10:49 UTC, artemgolozubov submitted a review, later dismissed
LGTM

2020-10-01 13:47 UTC, RommeroInCountry approved these changes
LGTM

2020-10-01 14:01 UTC, artemgolozubov approved these changes
LGTM

2020-10-01 14:04 UTC, merged