Fb sdk 266
incountry/sdk-nodejs pull request #171
Opened 2020-11-23 14:18 UTC by RommeroInCountry

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-XX](https://incountry.atlassian.net/browse/SDK-XX)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version in package.json? What is the new version?

2020-11-23 15:33 UTC, vadim-rutkevich-incountry commented on README.md
> -General info about files, limit and how they would be stored if one decided to upload.
Please use:
- General information about files, their limits and how they would be stored if you decide to upload them.

2020-11-23 15:40 UTC, vadim-rutkevich-incountry commented on README.md
> +InCountry Storage allows to attach files to previously created records. Attachments meta information is available via `attachments` field of `StorageRecord` object.
Please use this:
InCountry Storage allows you to attach files to the previously created records. Attachments' meta information is available through the `attachments` field of the `StorageRecord` object.

2020-11-23 15:49 UTC, vadim-rutkevich-incountry commented on README.md
> +`addAttachment` method allows you to add or replace attachments.
Please correct:
The `addAttachment` method allows you to add or replace attachments.

2020-11-23 15:51 UTC, vadim-rutkevich-incountry commented on README.md
> +File data can be provided either as `Readable` stream, `Buffer` or `string` with path to the file in file system.
Please update:
File data can be provided either as `Readable` stream, `Buffer` or `string` with a path to the file in the file system.

2020-11-23 15:52 UTC, vadim-rutkevich-incountry commented on README.md
> +`deleteAttachment` method allows you to delete attachments using attachment's `fileId`.
Please update:
The `deleteAttachment` method allows you to delete attachments by using the attachment's `fileId`.

2020-11-23 15:53 UTC, vadim-rutkevich-incountry commented on README.md
> +`getAttachmentFile` method allows you to download attachment contents.
Please update:
The `getAttachmentFile` method allows you to download attachments.

2020-11-23 15:56 UTC, vadim-rutkevich-incountry commented on README.md
> +`getAttachmentMeta` method allows you can to retrieve attachment's metadata using attachment's `fileId`.
Please update:
The `getAttachmentMeta` method allows you to retrieve the attachment's metadata by using the attachment's `fileId`.

2020-11-23 16:01 UTC, vadim-rutkevich-incountry commented on README.md
> +`updateAttachmentMeta` method allows you to update attachment's metadata (mimetype and filename).
Please update:
The `updateAttachmentMeta` method allows you to update the attachment's metadata (MIME type and file name).

2020-11-23 16:03 UTC, vadim-rutkevich-incountry commented on README.md
> +### Deleting attachment
Please update:
### Deleting attachments

2020-11-24 12:53 UTC, VladimirLevitskiy requested changes

2020-11-24 12:53 UTC, VladimirLevitskiy commented on README.md
> +To access your data in InCountry Platform by using NodeJS SDK, you need to create an instance of the `Storage` class using the `createStorage` async factory method.
Is the capital letter at the word 'Platform' correct?

2020-11-24 12:53 UTC, VladimirLevitskiy commented on README.md
> +**WARNING** If the `hashSearchKeys` option is set to `false` the following string fields will have length limitation of 256 characters at most.
256 or 200?

2020-11-24 12:53 UTC, VladimirLevitskiy commented on README.md
> +You can also look up for data records by partial match using the `searchKeys` operator which performs partial match
special symbols are not supported, I recommend to add a phrase about it

2020-11-24 12:54 UTC, RommeroInCountry commented on README.md
> +To access your data in InCountry Platform by using NodeJS SDK, you need to create an instance of the `Storage` class using the `createStorage` async factory method.
yep, this one is intentional

2020-11-24 12:54 UTC, RommeroInCountry commented on README.md
> +**WARNING** If the `hashSearchKeys` option is set to `false` the following string fields will have length limitation of 256 characters at most.
256. 200 is for `search_keys` value

2020-11-24 13:10 UTC, VladimirLevitskiy approved these changes
LGTM

2020-11-24 13:20 UTC, artemgolozubov requested changes
Pls fix the phrase describing getAttachmentMeta

2020-11-24 13:20 UTC, artemgolozubov commented on README.md
> +Below you can find the example of how to  create a storage instance with oAuth credentials (and also provide a custom oAuth endpoint):
```suggestion
Below you can find the example of how to create a storage instance with oAuth credentials (and also provide a custom oAuth endpoint):
```

2020-11-24 13:20 UTC, artemgolozubov commented on README.md
> +search (similar to the `LIKE` SQL operator, without special symbols) within records text fields `key1, key2, ..., key10`.
```suggestion
search (similar to the `LIKE` SQL operator, without special characters) within records text fields `key1, key2, ..., key10`.
```

2020-11-24 13:20 UTC, artemgolozubov commented on README.md
> +//with data in Stream
```suggestion
// using data in Stream
```

2020-11-24 13:20 UTC, artemgolozubov commented on README.md
> +// with file path
```suggestion
// using file path
```

2020-11-24 13:20 UTC, artemgolozubov commented on README.md
> +The `getAttachmentMeta` method allows you can to retrieve attachment's metadata using attachment's `fileId`.
Fix this phrase pls

2020-11-24 13:42 UTC, VladimirLevitskiy approved these changes

2020-11-24 13:44 UTC, artemgolozubov approved these changes
LGTM

2020-11-24 13:47 UTC, merged