SDK-166 [Node.js SDK] Improve SDK errors handling
incountry/sdk-nodejs pull request #176
Opened 2020-12-07 14:13 UTC by artemgolozubov

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-166](https://incountry.atlassian.net/browse/SDK-166)

Code Quality (Before submitting PR)
------------
- [x] Ensure code compiles and passes Sonar Lint.
- [x] Do your best to ensure integration tests pass. If they don't then...
- [x] Remove, ignore, or mark pending any brittle tests.
- [x] Remove commented out code.

Target Release
--------------
- [x] Please put the target release vehicle this needs to be bundled with.
- [x] Did you increment the version in package.json? What is the new version?

2020-12-09 10:49 UTC, igor-alekseev-dev commented on src/errors.ts
> +class NetworkError extends StorageServerError {
NetworkError looks like a system error. Maybe rename to StorageNetworkError not to confuse users.

2020-12-09 10:49 UTC, igor-alekseev-dev commented on src/validation/utils.ts
> +  if (code && code !== '' && !Number.isNaN(+code)) {
What type of "code" you are expecting?

2020-12-09 12:38 UTC, artemgolozubov commented on src/api-client.ts
> +    if (!Number.isNaN(+e.code) && e.code === 401) {
Will fix, thx)

2020-12-09 12:41 UTC, artemgolozubov commented on src/validation/utils.ts
> +  if (code && code !== '' && !Number.isNaN(+code)) {
If the code is integer - `toStorageServerError()` should return `StorageServerError`. This check should be replaced with `Number.isInteger()`. I have no idea how did I miss that. I'll fix it, thank you!

2020-12-09 12:45 UTC, artemgolozubov commented on src/errors.ts
> +class NetworkError extends StorageServerError {
@RommeroInCountry What do you think?

2020-12-10 11:17 UTC, RommeroInCountry commented on src/errors.ts
> +class NetworkError extends StorageServerError {
StorageNetworkError looks fine :)

2020-12-10 12:44 UTC, igor-alekseev-dev submitted a review, later dismissed

2020-12-14 13:28 UTC, RommeroInCountry commented on src/api-client.ts
> +    if (strCode.match('EHOSTUNREACH') || strCode.match('ENOTFOUND')) {
are we sure we need to throw StorageConfigValidationError in this case? What if server goes down?

2020-12-14 13:35 UTC, RommeroInCountry commented on src/errors.ts
> +  static HTTP_ERROR_UNPROCESSABLE_ENTITY = 422;
can't find this status code in PoPAPI codebase

2020-12-14 14:09 UTC, RommeroInCountry requested changes

2020-12-14 16:25 UTC, artemgolozubov commented on src/errors.ts
> +  static HTTP_ERROR_UNPROCESSABLE_ENTITY = 422;
After discussion we decided to make code not obligatory in StorageServerError to avoid spoofing the original PoPAPI response code with the hardcoded one.

2020-12-14 16:27 UTC, artemgolozubov commented on src/api-client.ts
> +    if (strCode.match('EHOSTUNREACH') || strCode.match('ENOTFOUND')) {
After discussion we decided to leave it as is

2021-01-15 09:57 UTC, igor-alekseev-dev approved these changes

2021-01-20 16:56 UTC, RommeroInCountry approved these changes
LGTM - please update README either here or in the next PR

2021-01-22 10:55 UTC, merged