SDK-252 [Node.js SDK] AWS KMS Key integration example
incountry/sdk-nodejs pull request #181
Opened 2021-01-19 13:06 UTC by artemgolozubov

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-252](https://incountry.atlassian.net/browse/SDK-252)

Code Quality (Before submitting PR)
------------
- [x] Ensure code compiles and passes Sonar Lint.
- [x] Do your best to ensure integration tests pass. If they don't then...
- [x] Remove, ignore, or mark pending any brittle tests.
- [x] Remove commented out code.

Target Release
--------------
- [x] Please put the target release vehicle this needs to be bundled with.
- [x] Did you increment the version in package.json? What is the new version?

2021-01-19 16:32 UTC, VladimirLevitskiy submitted a review, later dismissed

2021-01-19 16:52 UTC, igor-alekseev-dev commented on examples/aws-kms.js
> +  await storage.delete(COUNTRY_CODE, newRecord.recordKey);
Inglourious ending :)

2021-01-20 10:05 UTC, igor-alekseev-dev submitted a review, later dismissed

2021-01-20 16:40 UTC, RommeroInCountry commented on examples/aws-kms.js
> +    serviceKey2: 'Test AWS KMS keys in Node.js SDK',
let's not use serviceKey's in examples, just in case ;)

2021-01-20 16:45 UTC, RommeroInCountry requested changes

2021-01-20 16:45 UTC, RommeroInCountry commented on examples/.eslintrc
> +        "import/no-extraneous-dependencies": "off",
I'd simply mute eslint in example file rather than hurting our own SDK

2021-01-20 16:45 UTC, RommeroInCountry commented on README.md
> +For a detailed example of AWS KMS keys usage please see [examples/aws-kms.js](examples/aws-kms.js)
The suggested use case assumes AWS user already got his KMS encrypted data key generated. Afterwards the key gets decrypted using AWS Node.js client library (`aws-sdk/clients/kms`) and then provided to SDK's `getSecrets()` function

2021-01-22 09:04 UTC, artemgolozubov commented on examples/.eslintrc
> +        "import/no-extraneous-dependencies": "off",
Please pay attention that it isn't the whole project eslint file, it's eslint file only for the `/examples` directory

2021-01-22 11:50 UTC, igor-alekseev-dev submitted a review, later dismissed

2021-01-28 16:27 UTC, RommeroInCountry requested changes

2021-01-28 16:27 UTC, RommeroInCountry commented on README.md
> +## AWS KMS encryption keys support
Let's call it "AWS KMS integration"

2021-01-28 16:27 UTC, RommeroInCountry commented on README.md
> +InCountry NodeJS SDK supports usage of AWS KMS encryption keys of type `AES_256` produced by symmetric master key (CMK).
InCountry NodeJS SDK supports usage of any 32-byte (256bit) AES key, including ones produced by AWS KMS symmetric master key (CMK).

2021-01-28 16:27 UTC, RommeroInCountry commented on README.md
> +The suggested use case assumes that AWS user already got his KMS encrypted data key generated. Afterwards the key gets decrypted using AWS Node.js client library (`aws-sdk/clients/kms`) and then prov
... got his KMS encrypted data key (AES_256) generated

2021-01-29 12:41 UTC, RommeroInCountry approved these changes
LGTM

2021-01-29 14:42 UTC, igor-alekseev-dev approved these changes

2021-01-29 14:49 UTC, merged