SDK-294 find options sort
incountry/sdk-nodejs pull request #183
Opened 2021-01-22 13:11 UTC by igor-alekseev-dev

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-XX](https://incountry.atlassian.net/browse/SDK-XX)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version in package.json? What is the new version?

2021-01-25 10:07 UTC, artemgolozubov approved these changes
LGTM

2021-01-26 17:04 UTC, RommeroInCountry commented on src/validation/find-options.ts
> +import * as t from 'io-ts';
no searching by parent_key/parentKey?

2021-01-26 17:10 UTC, RommeroInCountry commented on tests/unit/validation/find-options-tests.ts
> +  describe('.is()', () => {
is() ?

2021-01-26 17:10 UTC, RommeroInCountry requested changes
Please add README section as well

2021-01-26 17:13 UTC, igor-alekseev-dev commented on src/validation/find-options.ts
> +import * as t from 'io-ts';
Do you mean no sorting by parentKey?

2021-01-26 17:14 UTC, igor-alekseev-dev commented on tests/unit/validation/find-options-tests.ts
> +  describe('.is()', () => {
Yes, the method name is `is`

2021-01-27 10:44 UTC, artemgolozubov approved these changes
LGTM

2021-01-27 11:45 UTC, artemgolozubov submitted a review, later dismissed
LGTM

2021-01-27 15:09 UTC, RommeroInCountry requested changes

2021-01-27 15:09 UTC, RommeroInCountry commented on README.md
> +The `options` parameter defines the `limit` - number of records that are returned, the `offset`- the starting index used for record pagination, and the `sort` - for the list of keys to sort the resul
The overall tone of the sentence is kinda bulky. Let's change it this way.

The `options` parameter provides the following choices to manipulate the search results:
- `limit` - allows to limit the total number of records returned;
- `offset` - allows to specify the starting index used for records pagination;
- `sort` - allows to sort the returned records by one or multiple keys;

2021-01-28 09:01 UTC, artemgolozubov approved these changes
LGTM

2021-01-28 15:46 UTC, RommeroInCountry approved these changes
LGTM

2021-01-28 15:57 UTC, merged