SDK-301 [Node.js SDK] Update Readme with new errors description
incountry/sdk-nodejs pull request #184
Opened 2021-01-25 15:06 UTC by artemgolozubov

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-301](https://incountry.atlassian.net/browse/SDK-301)

Code Quality (Before submitting PR)
------------
- [x] Ensure code compiles and passes Sonar Lint.
- [x] Do your best to ensure integration tests pass. If they don't then...
- [x] Remove, ignore, or mark pending any brittle tests.
- [x] Remove commented out code.

Target Release
--------------
- [x] Please put the target release vehicle this needs to be bundled with.
- [x] Did you increment the version in package.json? What is the new version?

2021-01-25 15:08 UTC, igor-alekseev-dev approved these changes

2021-01-26 16:53 UTC, RommeroInCountry requested changes

2021-01-26 16:53 UTC, RommeroInCountry commented on README.md
> +- **StorageClientError** - used for various errors related to Storage configuration. All of the errors classes `StorageConfigValidationError`, `SecretsProviderError`, `SecretsValidationError`, `Input
All of the errors classes `StorageConfigValidationError`, `SecretsProviderError`, `SecretsValidationError`, `InputValidationError`, `StorageAuthenticationError` inherits from `StorageClientError`.
to
`StorageConfigValidationError`, `SecretsProviderError`, `SecretsValidationError`, `InputValidationError`, `StorageAuthenticationError` are inherited from `StorageClientError`.

2021-01-26 16:53 UTC, RommeroInCountry commented on README.md
> +- **StorageNetworkError** - thrown if SDK failed to communicate with InCountry servers due to network issues, such as request timeout, unreachable `endpoint` etc. Inherits from `StorageServerError`.
Inherited from

2021-01-28 15:47 UTC, RommeroInCountry approved these changes
LGTM

2021-01-28 15:57 UTC, igor-alekseev-dev approved these changes

2021-01-28 16:32 UTC, merged