SDK-302 [Node.js SDK] Allow oAuth2 token Storage initialization
incountry/sdk-nodejs pull request #187
Opened 2021-02-16 17:34 UTC by artemgolozubov

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-302](https://incountry.atlassian.net/browse/SDK-302)

Code Quality (Before submitting PR)
------------
- [x] Ensure code compiles and passes Sonar Lint.
- [x] Do your best to ensure integration tests pass. If they don't then...
- [x] Remove, ignore, or mark pending any brittle tests.
- [x] Remove commented out code.

Target Release
--------------
- [x] Please put the target release vehicle this needs to be bundled with.
- [x] Did you increment the version in package.json? What is the new version?

2021-02-17 13:35 UTC, RommeroInCountry requested changes

2021-02-17 13:35 UTC, RommeroInCountry commented on README.md
> +    token?: string;         // Used when OAuth token is already received by SDK user. Mutually exclusive with clientId, clientSecret, authEndpoints
Used when OAuth token is already acquired prior to Storage initialization.

2021-02-17 13:35 UTC, RommeroInCountry commented on README.md
> +The SDK also allows to use already received OAuth tokens if needed. In this mode SDK user is responsible for OAuth token receiving and renewal. Use this option only at your own risk.
"... to use previously acquired oAuth tokens if needed. In this mode SDK is not responsible for oAuth token renewal and it should be done by SDK user himself"

Let's also drop "risk" sentence :)

2021-02-17 13:35 UTC, RommeroInCountry commented on README.md
> +Below you can find the example of how to specify OAuth token while creating a storage instance:
storage -> Storage

2021-02-19 08:42 UTC, igor-alekseev-dev commented on src/validation/storage-options.ts
> +const OAuthOptionsIO: t.Type<OAuthOptions> = new t.Type(
Maybe we can simplify this to `t.union([ A, B ])` ?

2021-02-19 08:45 UTC, igor-alekseev-dev commented on src/validation/storage-options.ts
>    clientSecret: t.string,
Are `clientId` and `clientSecret` really optional within OAuth credentials?

2021-02-19 08:46 UTC, igor-alekseev-dev approved these changes

2021-02-19 09:56 UTC, artemgolozubov commented on src/validation/storage-options.ts
>    clientSecret: t.string,
Yeah, 
```
{
  ...,
  oauth: {},
}
```
is a valid config. Client id + secret could be specified in environment variables)

2021-02-23 12:11 UTC, RommeroInCountry approved these changes

2021-02-23 14:19 UTC, igor-alekseev-dev approved these changes

2021-02-23 14:53 UTC, merged