SDK-306 [Node.js SDK] add Schema 2.4 support
incountry/sdk-nodejs pull request #192
Opened 2021-02-24 11:16 UTC by igor-alekseev-dev

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-306](https://incountry.atlassian.net/browse/SDK-306)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version in package.json? What is the new version?

2021-02-24 11:58 UTC, RommeroInCountry requested changes

2021-02-24 11:58 UTC, RommeroInCountry commented on src/auth-client.ts
> +  invalid_grant: 'The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expires, revoked, does not match the redirection URI used in the
expired :)

2021-03-05 12:31 UTC, RommeroInCountry commented on README.md
> +**WARNING** The data with `expiresAt` will be vanished when time comes ))).
Records with non-null `expiresAt` value will be automatically deleted upon reaching the specified date.

2021-03-05 12:34 UTC, RommeroInCountry commented on src/validation/user-input/find-options.ts
>      return left('Only "asc" and "desc" is allowed as sorting direction');
direction => order (sort order)

2021-03-05 12:36 UTC, RommeroInCountry commented on src/validation/user-input/storage-record-data-array.ts
> +const STORAGE_RECORD_DATA_ARRAY_TOO_BIG_ERROR = `You must pass array of not more than ${MAX_RECORDS_IN_BATCH} records`;
You mast pass an array not larger than X records

2021-03-08 13:21 UTC, RommeroInCountry submitted a review, later dismissed

2021-03-08 14:29 UTC, artemgolozubov approved these changes
LGTM in general, but fix the typos please

2021-03-08 14:29 UTC, artemgolozubov commented on src/validation/user-input/find-filter.ts
> +const SEARCH_FIELD_LENGTH_ERROR_MESSAGE = `filter.${SEARCH_FIELD} should be at least ${SEARCH_FIELD_MIN_LENGTH} but not more than ${SEARCH_FIELD_MAX_LENGTH}`;
```suggestion
const SEARCH_FIELD_LENGTH_ERROR_MESSAGE = `filter.${SEARCH_FIELD} length should be between ${SEARCH_FIELD_MIN_LENGTH} and ${SEARCH_FIELD_MAX_LENGTH} chars`;
```

2021-03-08 14:29 UTC, artemgolozubov commented on src/validation/user-input/storage-record-data-array.ts
> +const STORAGE_RECORD_DATA_ARRAY_TOO_BIG_ERROR = `You mast pass an array not larger than ${MAX_RECORDS_IN_BATCH} records`;
```suggestion
const STORAGE_RECORD_DATA_ARRAY_TOO_BIG_ERROR = `You must pass an array not larger than ${MAX_RECORDS_IN_BATCH} records`;
```

2021-03-08 14:29 UTC, artemgolozubov commented on tests/unit/api-client-test.ts
> +          //
Do we need this empty comment?

2021-03-08 15:58 UTC, RommeroInCountry requested changes

2021-03-08 15:58 UTC, RommeroInCountry commented on src/validation/user-input/find-filter.ts
> +const SEARCH_FIELD_LENGTH_ERROR_MESSAGE = `filter.${SEARCH_FIELD} should be length should be between ${SEARCH_FIELD_MIN_LENGTH} and ${SEARCH_FIELD_MAX_LENGTH} chars`;
still a typo %)

2021-03-09 10:12 UTC, artemgolozubov submitted a review, later dismissed
LGTM

2021-03-09 10:22 UTC, artemgolozubov approved these changes
LGTM

2021-03-09 10:34 UTC, RommeroInCountry approved these changes

2021-03-09 10:42 UTC, merged