SDK-310 [Node.js SDK] write and batchWrite should return data from PoPAPI response
incountry/sdk-nodejs pull request #207
Opened 2021-05-04 11:38 UTC by artemgolozubov

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-310](https://incountry.atlassian.net/browse/SDK-310)

Code Quality (Before submitting PR)
------------
- [x] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [x] Remove, ignore, or mark pending any brittle tests.
- [x] Remove commented out code.

Target Release
--------------
- [x] Please put the target release vehicle this needs to be bundled with.
- [x] Did you increment the version in package.json? What is the new version?

2021-05-12 15:47 UTC, RommeroInCountry commented on src/storage.ts
> +        ...recordData,
let's have a chat on this tomorrow. We have separate opinions on whether just copy dates or decrypt response and return the server data to the user. I'd vote for the last but let's ask others

2021-05-28 11:54 UTC, igor-alekseev-dev requested changes

2021-05-28 11:54 UTC, igor-alekseev-dev commented on README.md
> +interface StorageRecordWrittenData extends StorageRecordData {
I thought we will name StorageRecordData (ApiRecordData) before saving and StorageRecord (ApiRecord) after saving. StorageRecord is already defined.

2021-05-28 16:36 UTC, artemgolozubov commented on README.md
> +interface StorageRecordWrittenData extends StorageRecordData {
We can't use StorageRecord here since we don't want to decrypt the returned record. StorageRecordWrittenData has some fields missing from StorageRecord.

2021-05-31 08:36 UTC, igor-alekseev-dev commented on README.md
> +interface StorageRecordWrittenData extends StorageRecordData {
I don't get it. We need to return StorageRecord from type as a result of public method.

2021-09-20 14:04 UTC, igor-alekseev-dev approved these changes

2021-09-21 11:59 UTC, RommeroInCountry requested changes

2021-09-21 11:59 UTC, RommeroInCountry commented on src/storage.ts
> +        const decryptedRecord = await this.decryptPayload(apiRecord, requestOptions.meta);
Please do a simple comparison that sent data is equal to received one.
Python compares records key by key throwing the following error in case of mismatch
`response validation failed. Return data doesn't match the one sent. Key mismatch: {key}"`

2021-09-21 11:59 UTC, RommeroInCountry commented on src/storage.ts
> +        return { records: decryptedRecords };
same for batchWrite

2021-09-21 11:59 UTC, RommeroInCountry commented on README.md
> +): Promise<StorageRecord> {
1) we really need this { record: recordData } return type to allow for future extensions if needed.

2021-09-22 11:30 UTC, igor-alekseev-dev commented on src/storage.ts
> +        const decryptedRecord = await this.decryptPayload(apiRecord, requestOptions.meta);
It'a very strange case - input data has valid format, POPAPI response has valid format but actual values differ.

2021-09-22 15:06 UTC, igor-alekseev-dev approved these changes

2021-09-22 15:11 UTC, RommeroInCountry approved these changes

2021-09-22 15:12 UTC, merged