SDK-328 [Node.js SDK] add healthcheck method
incountry/sdk-nodejs pull request #208
Opened 2021-05-06 10:54 UTC by artemgolozubov

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-328](https://incountry.atlassian.net/browse/SDK-328)

Code Quality (Before submitting PR)
------------
- [x] Ensure code compiles and passes Sonar Lint.
- [x] Do your best to ensure integration tests pass. If they don't then...
- [x] Remove, ignore, or mark pending any brittle tests.
- [x] Remove commented out code.

Target Release
--------------
- [x] Please put the target release vehicle this needs to be bundled with.
- [x] Did you increment the version in package.json? What is the new version?

2021-05-06 14:02 UTC, igor-alekseev-dev approved these changes

2021-05-12 16:00 UTC, RommeroInCountry requested changes

2021-05-12 16:21 UTC, artemgolozubov commented on src/storage.ts
> +  }
There will be an exception raised in case of 4xx or 5xx response code. See https://github.com/incountry/sdk-nodejs/blob/master/tests/unit/api-client-test.ts#L297
And I think that it won't be a problem if POPAPI will return 2xx code (for example) instead of 200 and we'll return `{ result: true }` in such case.

2021-05-28 10:50 UTC, RommeroInCountry approved these changes

2021-05-28 11:15 UTC, igor-alekseev-dev approved these changes

2021-05-28 11:19 UTC, merged