SDK-370 [Node.js SDK] store encryption keys in Node crypto container
incountry/sdk-nodejs pull request #223
Opened 2021-08-27 14:16 UTC by igor-alekseev-dev

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-370](https://incountry.atlassian.net/browse/SDK-370)

Code Quality (Before submitting PR)
------------
- [x] Ensure code compiles and passes Sonar Lint.
- [x] Do your best to ensure integration tests pass. If they don't then...
- [x] Remove, ignore, or mark pending any brittle tests.
- [x] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version in package.json? What is the new version?

2021-08-31 15:50 UTC, RommeroInCountry requested changes

2021-08-31 15:50 UTC, RommeroInCountry commented on src/validation/user-input/secrets-data.ts
> +    secret, isKey, isForCustomEncryption: isForCustomEncryptionOptional, version,
isForCustomEncryptionOptional -> isForCustomEncryptionValue. Otherwise the naming is kinda misleading

2021-08-31 15:50 UTC, RommeroInCountry commented on src/validation/user-input/secrets-data.ts
> +    secret, isKey, isForCustomEncryption: isForCustomEncryptionOptional, version,
or, as an alternative -
`const secretIsForCustomEncryption = isForCustomEncryption === true;`

2021-08-31 15:50 UTC, RommeroInCountry commented on src/validation/user-input/secrets-data.ts
> -  }
this check was actually kinda useful. This way you won't need to do things like `if (!isForCustomEncryption && decoded.length !== KEY_SIZE)`, `if (!isForCustomEncryption && secret.symmetricKeySize !== KEY_SIZE) {`, etc.

You can even just return secret asap as long it's for custom encryption and ignore this param further down the scope

2021-08-31 15:50 UTC, RommeroInCountry commented on src/validation/user-input/secrets-data.ts
> +const hasSecretOfCurrentVersion = (o: SecretsData): Either<string, SecretsData> => o.secrets.findIndex((s) => s.version === o.currentVersion) !== -1 ? right(o) : left('SecretsData has to have item wi
SecretsData has to have item with currentVersion -> None of the secrets in SecretsData match currentVersion

2021-08-31 15:50 UTC, RommeroInCountry commented on tests/unit/in-crypt-tests.ts
> -    });
there should be an exception anyways, but with other error message, isn't it?

2021-08-31 15:56 UTC, igor-alekseev-dev commented on src/validation/user-input/secrets-data.ts
> -  }
Nope. It was a limitation for custom encryption secrets. And now they can be strings, base64 strings and KeyObject like normal secrets. But without `isForCustomEncryption` flag more checks are applied to each kind.

2021-09-01 10:19 UTC, igor-alekseev-dev commented on package.json
> +    "@types/node": "12.20.21",
Because we support Nodejs 12 so we need intellisense for that version.

2021-09-01 15:33 UTC, RommeroInCountry commented on src/validation/user-input/secrets-data.ts
> -  }
It wasn't a limitation, was it? 
Isn't is just a check that disallows sending things like?
`{ isKey: true, secret: "xxx", isForCustomEncryption: true}`

2021-09-01 15:35 UTC, RommeroInCountry commented on src/validation/user-input/secrets-data.ts
> -  }
`isKey` is basically a flag that the supplied secret is a key for default encryption.

2021-09-03 10:28 UTC, RommeroInCountry requested changes

2021-09-03 10:28 UTC, RommeroInCountry commented on README.md
> +      secret: createSecretKey(Buffer.from('ABC...IHN0cmluZw==', 'base64')), // KeyObject with 32 byte key
please provide `const { createSecretKey } = require("crypto")` in the very header of this code snippet

2021-09-03 10:33 UTC, RommeroInCountry approved these changes

2021-09-03 10:36 UTC, artemgolozubov reviewed
Please take a look at the comments. The rest LGTM.

2021-09-03 10:36 UTC, artemgolozubov commented on src/in-crypt.ts
> +    const decipher = crypto.createDecipheriv('aes-256-gcm', key.export(), iv);
Do we need to call `key.export()` here? Looks like `createDecipheriv` accepts KeyObject as key parameter https://nodejs.org/api/crypto.html#crypto_crypto_createdecipheriv_algorithm_key_iv_options

2021-09-03 10:36 UTC, artemgolozubov commented on src/in-crypt.ts
> +    return decipher.update(encrypted) + decipher.final('utf8');
According to the docs `decipher.update(encrypted)` should return `Buffer`
> If no outputEncoding is provided, a Buffer is returned.

And `decipher.final('utf8')` returns `string`
> If outputEncoding is specified, a string is returned.

Are you sure this line is correct?

https://nodejs.org/api/crypto.html#crypto_decipher_update_data_inputencoding_outputencoding
https://nodejs.org/api/crypto.html#crypto_decipher_final_outputencoding

2021-09-03 10:50 UTC, igor-alekseev-dev commented on src/in-crypt.ts
> +    const decipher = crypto.createDecipheriv('aes-256-gcm', key.export(), iv);
Current NodeJS v16 yes but for v12 we need.

2021-09-03 12:27 UTC, artemgolozubov submitted a review, later dismissed
LGTM

2021-09-06 11:38 UTC, RommeroInCountry approved these changes

2021-09-06 11:42 UTC, artemgolozubov approved these changes
LGTM

2021-09-07 19:33 UTC, merged