SDK-437 [Node.js SDK] Add microseconds support
incountry/sdk-nodejs pull request #224
Opened 2021-09-08 08:46 UTC by igor-alekseev-dev

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-437](https://incountry.atlassian.net/browse/SDK-437)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version in package.json? What is the new version?

2021-09-14 17:00 UTC, artemgolozubov reviewed
Please fix test names. Also _underscores _in _storage _looks _ugly, _but _I'm not sure we need to fix this at the moment. And please take a look at the rest of comments.

2021-09-15 09:58 UTC, RommeroInCountry requested changes
We need an integration test suite covering the following case:
1. Create a record
2. Extract created_at from the record (be making a read request)
3. Make a find request using created_at value
4. Make sure find properly returns the expected record
5. Do the very same thing with updated_at and expires_at with microseconds

2021-09-15 09:58 UTC, RommeroInCountry commented on README.md
> +  expiresAt?: string | number | Date | MicroDate | null; // Accepts ISO-8601 formatted strings with microseconds, number timestamp with decimal microseconds, Date and MicroDate
number timestamp -> numeric timestamps
Date and MicroDate -> Date and MicroDate objects

2021-09-15 09:58 UTC, RommeroInCountry commented on README.md
> +SDK accepts ISO-8601 formatted strings, e.g '2021-03-11T17:23:05.941Z', number timestamp with decimal microseconds, Date and MicroDate.
number timestamp -> numeric timestamps
Date and MicroDate -> Date and MicroDate objects

2021-09-15 09:58 UTC, RommeroInCountry commented on src/validation/date.ts
> +const DATE_ERROR_CANNOT_CREATE_MICRODATE = 'Cannot create MicroDate: Expected string, number, Date or MicroDate';
We can go further and add `Cannot create MicroDate: Expected string, number, Date or MicroDate. Got: ${value}`

2021-09-15 09:58 UTC, RommeroInCountry commented on tests/unit/storage/add-attachment-tests.ts
> +              .to.be.rejectedWith(InputValidationError, errorMessageRegExp('addAttachment() call: Validation Error:', COUNTRY_CODE_ERROR_MESSAGE))));
why and where this "call:" was introduced to the error stack trace?

2021-09-15 14:15 UTC, igor-alekseev-dev commented on tests/unit/storage/add-attachment-tests.ts
> +              .to.be.rejectedWith(InputValidationError, errorMessageRegExp('addAttachment() call: Validation Error:', COUNTRY_CODE_ERROR_MESSAGE))));
Former error message structure `Storage.addAttachment() call: addAttachment() Validation Error: aaa`
- `addAttachment() call:` added by `@nomalizeErrors` decorator 
- `addAttachment() Validation Error:` added by `@validate` decorator.



Current `addAttachment() call: Validation Error: aaa`. 

So error message became shorter and changed a little.

2021-09-15 14:41 UTC, igor-alekseev-dev commented on src/validation/date.ts
> +const DATE_ERROR_CANNOT_CREATE_MICRODATE = 'Cannot create MicroDate: Expected string, number, Date or MicroDate';
Received value is logged before this message

2021-09-17 14:12 UTC, RommeroInCountry submitted a review, later dismissed

2021-09-17 15:20 UTC, RommeroInCountry approved these changes

2021-09-20 09:36 UTC, artemgolozubov approved these changes
LGTM

2021-09-20 09:38 UTC, merged