EOS-281 SDK-453 [Node.js SDK] Add support for enhanced search
incountry/sdk-nodejs pull request #232
Opened 2021-10-27 13:48 UTC by igor-alekseev-dev

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-453](https://incountry.atlassian.net/browse/SDK-453)

Code Quality (Before submitting PR)
------------
- [x] Ensure code compiles and passes Sonar Lint.
- [x] Do your best to ensure integration tests pass. If they don't then...
- [x] Remove, ignore, or mark pending any brittle tests.
- [x] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version in package.json? What is the new version?

2021-11-15 11:50 UTC, RommeroInCountry requested changes
Let's bump version to 4.3.0 and add info on $like and $or to README. Codewise the PR is LGTM

2021-11-15 15:44 UTC, RommeroInCountry requested changes

2021-11-15 15:44 UTC, RommeroInCountry commented on README.md
> +Note: You can use either `searchKeys` or `$like`.
Note: You can use either `searchKeys` or `$like`, not both

2021-11-15 15:44 UTC, RommeroInCountry commented on README.md
> +- multiple criterion with `$or` operator:
multiple criteria

2021-11-16 09:31 UTC, artemgolozubov reviewed
Please fix typos, the rest LGTM

2021-11-16 09:31 UTC, artemgolozubov commented on README.md
> +    { key1: 'john': key2: 'smith' },
```suggestion
    { key1: 'john', key2: 'smith' },
```

2021-11-16 10:16 UTC, RommeroInCountry requested changes

2021-11-16 10:16 UTC, RommeroInCountry commented on README.md
> +
```suggestion
Note: currently, nested `$or` operators are not supported
```

2021-11-16 10:18 UTC, RommeroInCountry approved these changes

2021-11-16 11:11 UTC, artemgolozubov approved these changes
LGTM

2021-11-16 11:12 UTC, RommeroInCountry approved these changes

2021-11-16 11:22 UTC, merged