SDK-497 remove env variables
incountry/sdk-nodejs pull request #241
Opened 2021-12-28 13:10 UTC by igor-alekseev-dev

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-497](https://incountry.atlassian.net/browse/SDK-497)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version in package.json? What is the new version?

2021-12-29 07:32 UTC, artemgolozubov reviewed
Please take a look at the comments below

2021-12-29 07:32 UTC, artemgolozubov commented on tests/unit/storage/constructor-tests.ts
> +            await expect(createStorage({ environmentId: '', encrypt: false, oauth: { token: '' } })).not.to.be.rejected;
```suggestion
            await expect(createStorage({ environmentId: 'envId', encrypt: false, oauth: { clientId: 'clientId', clientSecret: 'clientSecret' } })).not.to.be.rejected;
```

2021-12-29 07:32 UTC, artemgolozubov commented on tests/unit/storage/constructor-tests.ts
> +                  .to.be.rejectedWith(StorageConfigValidationError, 'Storage.constructor() call: Validation Error: <StorageOptions>.oauth.clientSecret should be string but got undefined');
```suggestion
                  .to.be.rejectedWith(StorageConfigValidationError, 'Storage.constructor() call: Validation Error: <StorageOptions>.oauth.clientId should be string but got undefined');
```

2021-12-29 07:32 UTC, artemgolozubov commented on tests/unit/validation/storage-options-test.ts
> +  [false].forEach((withCustomEnc) => {
```suggestion
  [false, true].forEach((withCustomEnc) => {
```

2021-12-29 15:15 UTC, artemgolozubov submitted a review, later dismissed
LGTM

2022-01-05 13:34 UTC, RommeroInCountry requested changes

2022-01-05 13:34 UTC, RommeroInCountry commented on src/validation/user-input/storage-options.ts
> +    return left('Provide callback function for secretData');
Provide a valid function returning 'SecretsData' object as 'getSecrets' StorageOptions attribute

2022-01-06 09:09 UTC, artemgolozubov approved these changes
LGTM

2022-01-06 09:09 UTC, artemgolozubov commented on src/validation/utils.ts
> +const validateLength = <A extends { length: number }>(a: A): Either<string, A> => {
Looks like `A` could also be a string here, so error message 'Array must be non empty' will look quite weird.

2022-01-06 09:38 UTC, igor-alekseev-dev commented on src/validation/utils.ts
> +const validateLength = <A extends { length: number }>(a: A): Either<string, A> => {
It was an attempt to make `validateLength` more generic and accepts any type with `.length`

2022-01-06 09:39 UTC, igor-alekseev-dev commented on src/validation/utils.ts
> +const validateLength = <A extends { length: number }>(a: A): Either<string, A> => {
But it is still used only for array validation for now

2022-01-06 10:48 UTC, RommeroInCountry approved these changes

2022-01-06 10:59 UTC, merged