SDK-485 [Node.js SDK] SDK should use midpop if possible
incountry/sdk-nodejs pull request #243
Opened 2021-12-30 14:44 UTC by artemgolozubov

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-485](https://incountry.atlassian.net/browse/SDK-485)

Code Quality (Before submitting PR)
------------
- [x] Ensure code compiles and passes Sonar Lint.
- [x] Do your best to ensure integration tests pass. If they don't then...
- [x] Remove, ignore, or mark pending any brittle tests.
- [x] Remove commented out code.

Target Release
--------------
- [x] Please put the target release vehicle this needs to be bundled with.
- [x] Did you increment the version in package.json? What is the new version?

2022-01-03 09:59 UTC, igor-alekseev-dev approved these changes

2022-01-05 09:29 UTC, igor-alekseev-dev approved these changes

2022-01-05 10:51 UTC, RommeroInCountry requested changes

2022-01-05 10:51 UTC, RommeroInCountry commented on tests/unit/api-client-test.ts
> +          ]);
can we please have two cases - 1) when midPop goes first 2) when minipop goes first.

2022-01-05 12:18 UTC, artemgolozubov commented on tests/unit/api-client-test.ts
> +          ]);
Done

2022-01-05 12:21 UTC, RommeroInCountry approved these changes

2022-01-05 12:24 UTC, igor-alekseev-dev approved these changes

2022-01-05 12:25 UTC, merged