SDK-421 [Node.js SDK] SSE mode support
incountry/sdk-nodejs pull request #244
Opened 2022-01-03 09:25 UTC by igor-alekseev-dev

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-421](https://incountry.atlassian.net/browse/SDK-421)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version in package.json? What is the new version?

2022-01-05 10:07 UTC, artemgolozubov reviewed
Please take a look at the comments below

2022-01-05 10:07 UTC, artemgolozubov commented on README.md
> +SDK supports server side encryption mode. In this mode all the data encryption and hashing is performed server-side. The input data is sent as is.
```suggestion
SDK supports server side encryption mode. In this mode all the data encryption and hashing is performed server-side. The input data is sent to the InCountry platform as is.
```

2022-01-06 12:53 UTC, RommeroInCountry requested changes

2022-01-06 12:53 UTC, RommeroInCountry commented on src/storage.ts
> +  // encryptionEnabled: boolean;
do we need this commented-out code?

2022-01-06 12:53 UTC, RommeroInCountry commented on src/storage.ts
> +        if (!this.crypto) { // rethink this check
encryptionEnabled flag was useful. I'd keep it. 
Moreover - we better keep it to have encrypt=False case more understandable when reading the codebase

2022-01-06 12:53 UTC, RommeroInCountry commented on src/storage.ts
>    async validate(): Promise<void> {
let's consider renaming this method as it validates only crypto-part

2022-01-06 12:53 UTC, RommeroInCountry commented on tests/integration/common.ts
> -    encrypt: encryption,
as I mentioned above - let's keep this option for a little while. 
It helps to better understand/read the code

2022-01-06 12:53 UTC, RommeroInCountry commented on tests/unit/storage/compatibility-tests.ts
> +          throw new Error('dsdsd');
I'm not sure this is the way ;)

2022-01-06 12:53 UTC, RommeroInCountry commented on tests/unit/storage/constructor-tests.ts
> +        xit('should throw an error if encryption is enabled and no getSecrets() callback provided', async () => {
this one should be restored

2022-01-06 13:12 UTC, igor-alekseev-dev commented on src/storage.ts
> +        if (!this.crypto) { // rethink this check
Actually this check is for `getSecrets()` - no secret data nothing to migrate 
encryptionEnabled is not that useful - encryptionEnabled=false will use plain text encryption and crypto object will be created so I can't say it's very clear

2022-01-06 13:13 UTC, igor-alekseev-dev commented on src/storage.ts
>    async validate(): Promise<void> {
Maybe later there will be more parts to validate -- let's keep top level public method `validate()`

2022-01-06 13:14 UTC, igor-alekseev-dev commented on tests/integration/common.ts
> -    encrypt: encryption,
We can introduce internal flag but not option to pass into

2022-01-06 13:15 UTC, igor-alekseev-dev commented on tests/unit/storage/constructor-tests.ts
> +        xit('should throw an error if encryption is enabled and no getSecrets() callback provided', async () => {
Without flag no getSecrets() will lead to plain text encryption.

2022-01-07 12:30 UTC, artemgolozubov commented on README.md
> +  // Also support boolean values as backward compatibility:
```suggestion
  // Also supports boolean values as backward compatibility:
```

2022-01-07 12:30 UTC, artemgolozubov commented on README.md
> +  getSecrets?: Function;    // Used to fetch an encryption secret. Not compatible with serverSideEncryption.
```suggestion
  getSecrets?: Function;    // Used to fetch an encryption secret. Not compatible with server side encryption.
```

2022-01-07 12:30 UTC, artemgolozubov commented on README.md
> +  normalizeKeys?: boolean;  // If set as 'true', all keys are stored as lowercase. The default value is 'false'. Not compatible with serverSideEncryption.
```suggestion
  normalizeKeys?: boolean;  // If set to 'true', all keys are stored as lowercase. The default value is 'false'. Not compatible with server side encryption.
```

2022-01-07 12:30 UTC, artemgolozubov commented on README.md
> +  hashSearchKeys?: boolean; // Set to false to enable partial match search among record's text fields `key1, key2, ..., key20`. Defaults to true. Not compatible with serverSideEncryption
```suggestion
  hashSearchKeys?: boolean; // Set to false to enable partial match search among record's text fields `key1, key2, ..., key20`. Defaults to true. Not compatible with server side encryption
```

2022-01-07 12:30 UTC, artemgolozubov commented on README.md
> +Below you can find an example of how to use the `serverSideEncryption` option:
We have no such option, please change to `encrypt:...`

2022-01-07 12:30 UTC, artemgolozubov commented on src/storage.ts
> +          throw new StorageConfigValidationError('Migration not supported when encryption is not made locally');
🤔 
That's interesting, I'm not sure about this case. How the user will be able to migrate encrypted server-side data with encKey1 to encKey2? Will be a special tool for this somewhere? Or we need to allow them just to rewrite the existing data (with the new encKey2 server-side)?

2022-01-07 13:03 UTC, RommeroInCountry requested changes

2022-01-07 13:03 UTC, RommeroInCountry commented on src/storage.ts
> +    recordData.is_encrypted = Boolean(this.encryption.crypto);
is_encrypted should be false for ENCRYPTION.OFF. But crypto would exist anyways.
If this code update didn't affect any unit test - we need to add test for that.

2022-01-07 13:27 UTC, igor-alekseev-dev commented on src/validation/user-input/storage-options.ts
> +    if (hasCustomEncryptionConfigs) {
So you prefer exception for `hashSearchKeys` and `normalizeKeys` instead of silently switching?

2022-01-07 13:31 UTC, igor-alekseev-dev commented on src/storage.ts
> +    }
This won't work. Typescript (at least the version we currently using) won't guess when there is 'crypto' and when there is no

2022-01-07 13:59 UTC, RommeroInCountry commented on src/storage.ts
> +          throw new StorageConfigValidationError('Migration not supported when encryption is not made locally');
good question. I think that should be the case for key migration done with the help of migration microservice (which is yet to be done).
Migrate method should be used in case when user decides to conduct key management routines on his side.

2022-01-07 14:00 UTC, RommeroInCountry commented on src/validation/user-input/storage-options.ts
> +    if (hasCustomEncryptionConfigs) {
It's not really a silent switch but a warning to user that he won't get what he thinks he will get.

2022-01-10 09:15 UTC, igor-alekseev-dev commented on tests/unit/storage/write-tests.ts
> +          describeText: 'sse',
POPAPI validation when SSE is enabled does not accept /
"The following characters are not allowed in the record_key field: / (slash), \\n (new-line character), ? (question mark), # (pound key)"

2022-01-10 12:22 UTC, RommeroInCountry approved these changes

2022-01-10 12:39 UTC, artemgolozubov approved these changes
LGTM

2022-01-10 13:20 UTC, merged