SDK-510 [Node.js SDK] Move default constant values to a separate single file
incountry/sdk-nodejs pull request #251
Opened 2022-01-24 16:33 UTC by igor-alekseev-dev

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-510](https://incountry.atlassian.net/browse/SDK-510)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version in package.json? What is the new version?

2022-02-01 12:53 UTC, artemgolozubov approved these changes
LGTM

2022-02-01 13:08 UTC, artemgolozubov approved these changes
LGTM

2022-02-03 14:39 UTC, artemgolozubov submitted a review, later dismissed
LGTM

2022-02-07 12:19 UTC, RommeroInCountry requested changes

2022-02-07 12:19 UTC, RommeroInCountry commented on src/constants.ts
> +];
let's move these to the very bottom of this file (or even to a separate file). This variables are more business-logic rather than plain constants

2022-02-08 10:33 UTC, artemgolozubov approved these changes
LGTM

2022-02-08 10:44 UTC, RommeroInCountry approved these changes

2022-02-08 10:47 UTC, merged