SDK-532 [Node.js SDK] Proxy support
incountry/sdk-nodejs pull request #258
Opened 2022-03-21 10:00 UTC by artemgolozubov

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-532](https://incountry.atlassian.net/browse/SDK-532)

Code Quality (Before submitting PR)
------------
- [x] Ensure code compiles and passes Sonar Lint.
- [x] Do your best to ensure integration tests pass. If they don't then...
- [x] Remove, ignore, or mark pending any brittle tests.
- [x] Remove commented out code.

Target Release
--------------
- [x] Please put the target release vehicle this needs to be bundled with.
- [x] Did you increment the version in package.json? What is the new version?

2022-03-23 14:04 UTC, RommeroInCountry submitted a review, later dismissed

2022-03-28 10:15 UTC, igor-alekseev-dev commented on tests/integration/proxy-server-support-tests.ts
> +  server.listen(proxyPort, proxyHost);
Maybe it's better to return `server` instance here

2022-03-28 12:24 UTC, igor-alekseev-dev approved these changes

2022-03-28 13:03 UTC, RommeroInCountry requested changes
Please provide README updates for this feature

2022-03-28 15:50 UTC, RommeroInCountry requested changes

2022-03-28 15:50 UTC, RommeroInCountry commented on README.md
> +      };
Typo, should be ,

2022-03-28 15:50 UTC, RommeroInCountry commented on README.md
> +The SDK allows to use proxy server for all requests.
for all HTTP requests

2022-03-28 15:50 UTC, RommeroInCountry commented on README.md
> +Below you can find the example of how to specify your proxy server configuration:
an example

2022-03-28 15:56 UTC, RommeroInCountry requested changes

2022-03-28 15:56 UTC, RommeroInCountry commented on README.md
> +      };
Typo, should be ,

2022-03-28 16:11 UTC, RommeroInCountry approved these changes

2022-03-29 10:47 UTC, igor-alekseev-dev approved these changes

2022-03-29 10:55 UTC, merged